---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

notifications:
  email: false
  slack:
    secure: "Thb84ApXVAt8a7AGn74GFLDe0l1hpgZtkDQLWwdm+W5xiJjXs4mrEnf3qMwHQdjE9v6CBgrg5UPnV326YFvA2KgQ5J5pEt8l2iU+jlhQSSL0ZoMyB/5lAvtfb26Z67K+OJsPhX0YEtGqL4E7wVwmvatDGfr9kCJVNmTxPfUoBvIJOpGdHx8IXa+1VVPW021S52piTPLKV2/ckOODZryMwDDNeSuxhe3FZAFK16mDNP0pyRyQ24qd2oaWRd8pKLv3vDfUG/geVqTVB9RGsYNh0K2XFWhS/RIGt605d5mJanymny17ICy5zzlNoCO6LmVBP4QmBmO9prTfzgtqN9+EZxvhUDLnjD5wZONyn3554ZGqE4XETQQafsMIlb0q6GVmGCytQ5swhUUQHXUYmiVAtBl7UqImVBF1Cf2MulsPRnHtPkmMQfS9QqDgYOxDVD/24GQlnaDpwGB4V/YFiaHelaU6VWVU2QGc+RhMB2UQ5FdbPa3OoDJzPQVZm2KEyR08fBBInmBIcpL8ofH4QPqqHNZEsI5VVvZCsNytnBtMAzKFIwzB3VDU0LMVJwbzqSTgRDZV4AzUu1yfpa8dn9x2qZaVuGZGcegF5BEeJIlW8rEmNc+VKzzGLW+vi8j3AdaLuKCgEbezTvwbOvpu6bWy4zLrfJs1ZHNT9gQp5h23imU="
