include:
  - _pages

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Site settings
title: ember-talk
description: An ember-cli realtime chat application
lang: en_GB
url: https://ember-talk.com

# Build settings
markdown: kramdown
highlighter: rouge

# Analytics settings
analytics:
  google_tracking_id: UA-115455323-1
