include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-sitemap
  - jemoji

# Site settings
title: ember-talk
description: An ember-cli realtime chat application
lang: en_GB
url: https://ember-talk.com

# Build settings
markdown: kramdown
highlighter: rouge
